version: '3.5'
services:
  apache-symfony7:
    container_name: "apache-symfony7"
    #image: apache-symfony7:latest #for locally usage
    image: ityannred/apache-symfony7:latest
    ports:
      - "8032:80"
    volumes:
      - /home/yann/docker/firstFm:/home/web
    #restart: always
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#  NETWORK & VOLUMES
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# networks:
#   internal:
#     name: internal
#     driver: bridge